version: 0.2

env:
  parameter-store:
    AWS_DEFAULT_REGION: "/MEAN/AWS_DEFAULT_REGION"
    
phases:
  install:
    commands:
      - echo Installing NPM...
      - curl -sL https://rpm.nodesource.com/setup_6.x | sudo -E bash -
      - export NVM_DIR="$HOME/.nvm"
      - yum install nodejs --enablerepo=nodesource
      - echo Installing NPM Packages
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
