version: 0.2

env:
  parameter-store:
    AWS_DEFAULT_REGION: "/MEAN/AWS_DEFAULT_REGION"
    
phases:
  install:
    commands:
      - echo Installing NPM...
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
			- export NVM_DIR="$HOME/.nvm"
			- [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
			- [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      - nvm install 6.11.5
      - echo Installing NPM Packages
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
