version: 0.2

env:
  parameter-store:
    AWS_DEFAULT_REGION3: "/MEAN/AWS_DEFAULT_REGION"
    
phases:
  install:
    commands:
      - printenv 
      - echo Installing NPM...
      - sudo apt-get update 
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo apt-get install -y build-essential
      - echo Installing NPM Packages
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
